export const listaEnfermagem = [
  { label: 'Consciência', radio: ['Acordado', 'Orientado', 'Sonolento', 'Torporoso'] },
  { label: 'Hemodinâmico', radio: ['Afebril', 'Febril', 'Pirexia'] },
  { label: 'Cardiovascular', radio: ['Normocárdico', 'Bradicárdico', 'Taquicárdico'] },
  { label: "Pressão Arterial", radio: ['Normotenso', 'Hipertenso', 'Hipotenso'] },
  { label: "Respiratório", radio: ['Eupneico', 'Dispneico', 'Taquipneico'] },
  { label: "Mucosas", radio: ['Coradas', 'Hipocoradas'] },
  { label: "Integridade Cutânea", radio: ['Hidratada', 'Desidratada'] },
  { label: "MMSS", radio: ['Fragilidade Capilar', 'Edema', 'Íntegros'] },
  { label: "MMII", radio: ['Fragilidade Capilar', 'Edema', 'Íntegros'] },
  { label: "Aceitação da dieta", radio: ['Total', 'Parcial', 'Não Aceitou'] },
  { label: "Abdômen", radio: ['Globoso', 'Flácido', 'Peristáltico', 'Indolor', 'Dor'] },
  { label: "Eliminações", radio: ['Presente', 'Ausente', 'Fralda', 'Dor', 'Odor'] },
  { label: "Eliminações Intestinais", radio: ['Presente', 'Ausente', 'Constipação'] },
  { label: "Ausculta Pulmonar", radio: ['Normal', 'Anormal'] },
]

export const listaIdosos = [
  { id: 1, nome_idoso: "Maria da Paixão G. Teixeira", idade: 94 },
  { id: 2, nome_idoso: "Onelice Silva Campos", idade: 83 },
  { id: 3, nome_idoso: "Rosália dos Santos Rocha", idade: 95 },
  { id: 4, nome_idoso: "Maria Joanna da Silva Souza", idade: 88 },
  { id: 5, nome_idoso: "Wilson Ramos dos Santos", idade: 90 },
  { id: 6, nome_idoso: "Alex Rodrigues Correa", idade: 68 },
  { id: 7, nome_idoso: "Edime Maia de Oliveira", idade: 83 },
  { id: 8, nome_idoso: "Maria Helena Lobato Ferreira", idade: 92 },
  { id: 9, nome_idoso: "Vera da Silva Teixeira", idade: 85 },
  { id: 10, nome_idoso: "Penha da Conceição G.", idade: 75 },
  { id: 11, nome_idoso: "Marina Rios da Silva", idade: 87 },
  { id: 12, nome_idoso: "Luciene Maria L. de Moraes", idade: 74 },
  { id: 13, nome_idoso: "Luiz Casado Lima", idade: 92 },
  { id: 14, nome_idoso: "Ademir Gonçalves Mataruna", idade: 76 },
  { id: 15, nome_idoso: "Carmen Iacovino", idade: 95 },
  { id: 16, nome_idoso: "Celina Robertson", idade: 63 },
  { id: 17, nome_idoso: "Maria das Dores", idade: 95 }
]